name: Limelight Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build in Docker container	    
      uses: docker://mriffle/build-spectr:latest
      with:
        entrypoint: ant
        args: -f ant_build_all_create_download_zip_file.xml
