name: Release Workflow

on:
  release:
    types: [released]
    tags:
      - 'v*'

env:
  DOCKER_REPO_WEBAPP: "mriffle/spectr"

jobs:
  dockerhub:

    runs-on: mriffle/build-spectr:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker meta for webapp
      id: meta_webapp
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.DOCKER_REPO_WEBAPP }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}
    - name: Build and push webapp
      id: docker_build_webapp
      uses: docker/build-push-action@v2
      with:
        context: docker/webapp
        push: true
        tags: ${{ steps.meta_webapp.outputs.tags }}


  github_deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build in Docker container
        uses: docker://mriffle/build-limelight:latest
        with:
          entrypoint: ant
          args: -f ant_build_all_create_download_zip_file.xml
      - name: Upload zip file to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./download_zip_file/spectral_storage_service_deploy.zip
          asset_name: spectral_storage_service_deploy.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
